### ISSUE TITLE
Resampling not implemented

### ISSUE THREAD

**Issue by akonnerr** [usnistgov/NFIQ2#215]
![image](https://user-images.githubusercontent.com/49476535/114352609-a62c6f00-9b9e-11eb-8c9a-ab45f7b5c53e.png)

When using NFIQ2, no matter what fingerprint image is used, the error in the image above will appear(here is FVC2004);

At the same time, the fingerprint image I used is definitely 500ppi, but the following prompt still appears：
This Image is not 500 PPI. Would you like to re-sample this image to 500 PPI? (y/[N]): y

**Comment by gfiumara** [comment]
This would occur when the resolution encoded into the image cannot be determined (because it is missing, or because it is not 500 PPI). Use a tool like ImageMagick's `identify` to verify this. We have clarified this message in future code changes, so I will close this issue. 

We haven't posted pre-compiled versions with that message yet though. In the interim, you can use a tool like ImageMagick's convert to encode the density. Something like:

```bash
convert $input -density 500 -units PixelsPerInch $output
```

This will only overwrite the resolution portion of the image without changing pixel data.
