### ISSUE TITLE
program crash when using libNfiq2Api.so

### ISSUE THREAD

**Issue by indianscorpion** [usnistgov/NFIQ2#373]
program crash when using libNfiq2Api.so
program loaded all the functions, but failed at InitNfiq2.
#0  0xffffffffe9a88ea0 in ?? ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0xffffffffe9a88ea0 in ?? ()

**Comment by indianscorpion** [comment]
after debugging it, it seemed that crashing at this line.
char *h=NULL, *hash=NULL
 h = InitNfiq2(&hash);
entered InitNfiq2, but never returned.

**Comment by gfiumara** [comment]
You don't need dlsym, link the library instead. Works as expected.

Additionally, the C API is not supported, per the pre-processor definition that you have to set in order to build anything linking against this library. As I've said in your other closed issues, **please do not use it.** Closing this issue as a result.
